version: '0.2'
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - echo ID_w4xZqB6p
      - 'docker build -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile .'
      - 'docker tag $IMAGE_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG'
      - echo Building Maven project...
      - mvn clean package
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - 'docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG'
artifacts:
  files:
    - none
