version: '0.2'
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Setting up Maven...
      - mvn --version
  pre_build:
    commands:
      - 'echo Pre-build phase: Cleaning workspace...'
      - mvn clean
  build:
    commands:
      - echo Building the project using Maven...
      - sudo tar -czvf pln5000280.tar.gz *
  post_build:
    commands:
      - echo Build completed. Artifacts are ready for deployment.
artifacts:
  files:
    - pln5000280.tar.gz
